 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/product_tags", type: :request do
  # ProductTag. As you add validations to ProductTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductTag.create! valid_attributes
      get product_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_tag = ProductTag.create! valid_attributes
      get product_tag_url(product_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_product_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      product_tag = ProductTag.create! valid_attributes
      get edit_product_tag_url(product_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductTag" do
        expect {
          post product_tags_url, params: { product_tag: valid_attributes }
        }.to change(ProductTag, :count).by(1)
      end

      it "redirects to the created product_tag" do
        post product_tags_url, params: { product_tag: valid_attributes }
        expect(response).to redirect_to(product_tag_url(ProductTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductTag" do
        expect {
          post product_tags_url, params: { product_tag: invalid_attributes }
        }.to change(ProductTag, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post product_tags_url, params: { product_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested product_tag" do
        product_tag = ProductTag.create! valid_attributes
        patch product_tag_url(product_tag), params: { product_tag: new_attributes }
        product_tag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the product_tag" do
        product_tag = ProductTag.create! valid_attributes
        patch product_tag_url(product_tag), params: { product_tag: new_attributes }
        product_tag.reload
        expect(response).to redirect_to(product_tag_url(product_tag))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        product_tag = ProductTag.create! valid_attributes
        patch product_tag_url(product_tag), params: { product_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested product_tag" do
      product_tag = ProductTag.create! valid_attributes
      expect {
        delete product_tag_url(product_tag)
      }.to change(ProductTag, :count).by(-1)
    end

    it "redirects to the product_tags list" do
      product_tag = ProductTag.create! valid_attributes
      delete product_tag_url(product_tag)
      expect(response).to redirect_to(product_tags_url)
    end
  end
end
